version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - migration
    environment:
      DATABASE_URL: postgres://taxcalc@postgres/tax_calculator
  migration:
    build: .
    image: app
    command: node migration up
    volumes:
      - .:/usr/app/
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://taxcalc@postgres/tax_calculator
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: taxcalc
      POSTGRES_DB: tax_calculator